<div class="container">
    <div class="row">
        <div class="post-container">
            <h2 class="main-header">Post list</h2>
            <a href="" class="btn btn-success add-post-btn">Add new</a>
            <div class="add-post-container"></div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Id
                        <div class="order-container" id="id">
                            <span class="glyphicon glyphicon-triangle-top"></span>
                            <span class="glyphicon glyphicon-triangle-bottom active"></span>
                        </div>
                    </th>
                    <th>Title
                        <div class="order-container" id="title">
                            <span class="glyphicon glyphicon-triangle-top"></span>
                            <span class="glyphicon glyphicon-triangle-bottom"></span>
                        </div>
                    </th>
                    <th>Content
                        <div class="order-container" id="content">
                            <span class="glyphicon glyphicon-triangle-top"></span>
                            <span class="glyphicon glyphicon-triangle-bottom"></span>
                        </div>
                    </th>
                    <th>Author
                        <div class="order-container" id="author">
                            <span class="glyphicon glyphicon-triangle-top"></span>
                            <span class="glyphicon glyphicon-triangle-bottom"></span>
                        </div>
                    </th>
                    <th>Created at
                        <div class="order-container" id="created_at">
                            <span class="glyphicon glyphicon-triangle-top"></span>
                            <span class="glyphicon glyphicon-triangle-bottom"></span>
                        </div>
                    </th>
                    <th>Manage</th>
                </tr>
                </thead>
                <tbody>

                <?php foreach ($data['result'] as $post): ?>
                    <tr class="post-item" id="<?= $post->id ?>">
                        <td><?= $post->id; ?></td>
                        <td class="post-item-title">
                            <div class="post-title-value"><?= $post->title; ?></div>
                        </td>
                        <td class="post-item-content">
                            <div class="post-content-value"><?= $post->content; ?></div>
                        </td>
                        <td class="author"><?= $post->author ?></td>
                        <td class="created_at"><?= $post->created_at; ?></td>
                        <td class="post-manage-list">
                            <div class="post-manage-item">
                                <a href="" class="btn btn-danger delete-post-btn">Delete</a>
                                <a href="" class="btn btn-success edit-post-btn">Edit</a>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>

    <button type="button" class="btn btn-default btn-lg" id="scroller">
        <span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span>
    </button>
</div>

