<div class="container">
    <div class="row">
        <div class="post-container-list">
            <h2>Post list</h2>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Content</th>
                    <th>Author</th>
                    <th>Created at</th>
                    <th>Manage</th>
                </tr>
                </thead>
                <tbody>

                <?php foreach ($data['result'] as $post): ?>
                    <div class="post-item" id="<?= $post->id?>">
                        <tr>
                            <td><?= $post->id; ?></td>
                            <td><?= $post->title; ?></td>
                            <td><?= $post->content?></td>
                            <td><?= $post->author ?></td>
                            <td><?= $post->created_at; ?></td>
                            <td>
                                <div><a href="" class="btn btn-danger">Delete</a></div>
                            </td>
                        </tr>
                    </div>
                <?php endforeach; ?>

                </tbody>
            </table>
        </div>
        <div class="pagination-container">
            <ul class="pagination">
                <li class="page-item">
                    <a class="page-link" href="<?=ROOT_DIR?>index/<?= 1?>" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                <?php for ($i = 1; $i < $data['steps']; $i++): ?>
                    <li class="page-item <?= ($i == $data['active']) ? 'active' : null;?>"><a class="page-link" href="<?=ROOT_DIR?>index/<?= $i;?>"><?=$i;?></a></li>
                <?php endfor;?>
                <li class="page-item">
                    <a class="page-link" href="<?=ROOT_DIR?>index/<?=$i - 1;?>" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>