<div class="container">
    <div class="row">
        <div class="post-container">
            <h2 class="main-header">Post list</h2>
            <a href="" class="btn btn-success add-post-btn">Add new</a>
            <div class="add-post-container"></div>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Content</th>
                    <th>Author</th>
                    <th>Created at</th>
                    <th>Manage</th>
                </tr>
                </thead>
                <tbody>

                <?php foreach ($data['result'] as $post): ?>
                        <tr class="post-item" id="<?=$post->id?>">
                            <td><?= $post->id; ?></td>
                            <td class="post-item-title">
                                <div class="post-title-value"><?= $post->title; ?></div>
                            </td>
                            <td class="post-item-content">
                                <div class="post-content-value"><?= $post->content; ?></div>
                            </td>
                            <td class="author"><?= $post->author ?></td>
                            <td><?= gmdate("Y-m-d H:i:s", $post->created_at);?></td>
                            <td class="post-manage-list">
                                <div class="post-manage-item">
                                    <a href="" class="btn btn-danger delete-post-btn">Delete</a>
                                    <a href="" class="btn btn-success edit-post-btn">Edit</a>
                                </div>
                            </td>
                        </tr>
                <?php endforeach; ?>

                </tbody>
            </table>
        </div>
        <div class="pagination-container">
            <ul class="pagination">
                <li class="page-item">
                    <a class="page-link" href="<?=ROOT_DIR?>index/<?= 1?>" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                </li>
                <?php for ($i = 1; $i < $data['steps'] + 1; $i++): ?>
                    <li class="page-item <?= ($i == $data['active']) ? 'active' : null;?>"><a class="page-link" href="<?=ROOT_DIR?>index/<?= $i;?>"><?=$i;?></a></li>
                <?php endfor;?>
                <li class="page-item">
                    <a class="page-link" href="<?=ROOT_DIR?>index/<?=$i - 1;?>" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

